name: websafe_network_image
description: Simple abstraction to be able to detect Web, Android, and iOS without a hard reference to `dart:io`
version: 1.0.2
homepage: https://github.com/peiffer-innovations/websafe_network_image
environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.1.0+1
  http: ^0.12.1
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

