name: Flutter Publisher

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter packages get
    - name: Flutter Analyzer
      run: dartanalyzer lib
    - name: Code Format
      run: dartfmt --set-exit-if-changed -w lib test
    - name: Run tests
      run: flutter test
    - name: Publish
      uses: sakebook/actions-flutter-pub-publisher@v1.2.1
      with:
        credential: ${{ secrets.CREDENTIAL_JSON }}
        flutter_package: false
        skip_test: true
